
name: jupyterlab_documentation
channels:
  - conda-forge
dependencies:
- python=3.8
- sphinx>=1.8
- sphinx-copybutton
- pydata-sphinx-theme
- pytest
- pytest-tornasync
- pytest-check-links
- pip
- nodejs
- jsx-lexer
- myst-parser
