name: example-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyter-server-proxy
  - jupyterlab-link-share >=0.2
  - matplotlib-base
  - nodejs >=18,<19
  - numpy
  - pip
  - python >=3.11,<3.12
  - vega_datasets
  - xeus-python
  - yarn <2
  # build
  - hatchling >=1.5.0
  - hatch-jupyter-builder >=0.3.2
  # dev
  - black-jupyter
  - bump2version
  - hatch
  - pre-commit
  - pytest-cov
  - python-build
  - ruff
  # runtime deps
  - async-lru >=1.0.0
  - ipykernel
  - jinja2 >=3.0.3
  - jupyter_core
  - jupyter_server >=2.0.1,<3
  - jupyter-lsp >=1.5.1
  - jupyterlab_server >=2.19.0,<3
  - notebook-shim >=0.2
  - packaging
  - tornado >=6.2.0
  - traitlets
  # collaboration
  - jupyter_server_fileid >=0.7.0
  # extra conda stuff
  - jsonschema-with-format-nongpl
  # not yet on conda
  - pip:
    - jupyterlab-rtc >=0.0.5
